include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - avoid_print
    - prefer_single_quotes
    - always_use_package_imports
    - sort_pub_dependencies
